export default (appConstants = {
    ERROR: {
      EMAIL: 'Failed to send Email',
      FORCE_LOGOUT: 'Something went wrong, please login again',
      GEN: 'Something went wrong, please try again later',
      UN_AUTH: 'You are not authorized to access this',
      GOOGLE_API: 'Error in getting your location',
      LOGIN:
        'The phone number and role you have provided do not match any account. Please create a new account',
      NET: 'Please check your internet connection',
      SMS: 'Failed to send SMS',
      WHATSAPP: 'Failed to connect with WhatsApp',
    },
    WARNING: {
      ADD_NEW_ROLE: 'Please select a role before proceeding',
      ADDRESS_INV: 'Please enter a valid address',
      ADDRESS: 'Please enter an address',
      AGE_INV: 'You should be more than 18 years old to use this app',
      CITY: 'Please enter a valid city',
      CONFIRM_PASSWORD_MISMATCH:
        'Your password and confirmation password do not match',
      COUNTRY_INV: 'Please enter a valid country',
      CATEGORY: 'You need to select atleast one category',
      CATEGORY_OWN: 'You cannot uncheck this category',
      DELETE_ADDRESS: 'Are you sure you want to delete this address?',
      DELIVERY_CHARGES_INV: 'Please enter a valid delivery fee',
      DISCOUNT_INV: 'Please enter a valid discount amount',
      DISTANCE_INV: 'Distance should not be more than 10 km',
      EMAIL_INV: 'Please enter a valid email address',
      EMAIL: 'Please enter an email address',
      FEEDBACK: 'Please provide feedback first',
      GEN_BLANK_GEN: ' cannot be blank',
      GEN_BLANK: 'This field cannot be blank',
      GO_BACK: 'Do you really want to go back? It will discard all your changes',
      LOCATION_PERMISSION_DENIED: 'Location permission is denied by the user',
      LOCATION_PERMISSION_REVOKED:
        'Location permission is permanently revoked by the user',
      MOBILE_INV: 'Please provide valid mobile number',
      MOBILE: 'Please enter a mobile number',
      NAME_CHAR: 'The name must contain at least 2 characters',
      NAME_INV: 'Please enter a valid name',
      NAME: 'Please enter a name',
      NUMBER_INV: 'Please enter a valid number',
      NUMBER: 'Please enter a number',
      OTP_INV: 'Please enter a valid OTP',
      PASSWORD_INV_WHITE: 'Password should not contain any whitespaces',
      PASSWORD_INV: 'Password must contain at least 6 characters',
      PASSWORD_MISMATCH: 'Your old password does not match with our record',
      PASSWORD: 'Please enter a password',
      PAYMENT_INV: 'Please enter a valid payment amount',
      PINCODE_INV_1: 'Please enter a valid pincode',
      PINCODE_INV: 'Pincode must be of 6 digits',
      PINCODE: 'Please enter a pincode',
      PRICE_INV: 'Please enter a valid price',
      PRODUCT_INV: 'Please enter a valid product name',
      PRODUCT_INV_SPECIAL: 'Special charecters are not allowed',
      QUANTITY_INV: 'Please enter a valid quantity',
      SELECT_ROLE: 'You are only allowed to add one role at a time',
      SELECT_SELLER: 'Please select a seller before proceeding',
      SHOP_NAME_INV: 'Please enter a valid shop name',
      STATE_INV: 'Please enter a valid name of state',
      STD_UNIT_INV: 'Please enter a valid available unit',
      TNC: 'Please review and accept our terms and condition before procceding',
    },
    EMPTY_TEXTS: {
      REG_NEW_ROLE: 'Please wait while the available roles are loading',
      NO_PRODUCT: 'No item matches your search criteria',
      NO_PRODUCT_CAT:
        'This product is not available in #, please search in different category or use our master search',
      NO_CATEGORY: 'No categorie is found',
    },
    STANDARD_UOM: [
      {label: 'Packet', value: 'pkt'},
      {label: 'Kilogram', value: 'kg'},
      {label: 'Gram', value: 'gm'},
      {label: 'Litre', value: 'lt'},
      {label: 'Millilitre', value: 'ml'},
    ],
    STANDARD_UOM_SELLER: [
      {label: 'Price Per Packet', value: 'pkt'},
      {label: 'Price Per Kilogram', value: 'kg'},
      {label: 'Price Per Gram', value: 'gm'},
      {label: 'Price Per Litre', value: 'lt'},
      {label: 'Price Per Millilitre', value: 'ml'},
    ],
    ORDER_STATUS: [
      {label: 'Ordered', value: 1},
      {label: 'Revised by Seller', value: 2},
      {label: 'Completed by Seller', value: 3},
      {label: 'Accepted by Buyer', value: 4},
      {label: 'Cancelled by Buyer', value: 5},
      {label: 'Cancelled by Seller', value: 6},
      {label: 'Delivered', value: 7},
      {label: 'Undelivered', value: 9},
    ],
    AVAILABLE_GENDERS: [
      {label: 'Male', value: 'M'},
      {label: 'Female', value: 'F'},
      {label: 'Other', value: 'T'},
    ],
    AVAILABLE_MEALS: [
      {label: 'Vegetarian', value: 'Veg'},
      {label: 'Non Vegetarian', value: 'Non-Veg'},
      {label: 'Vegan', value: 'Vegan'},
    ],
    CURR_SYM: [
      {label: '₹', value: 91},
      {label: 'S$', value: 65},
      {label: '$', value: 1},
    ],
    ACCEPT_ORDER: 'Are you accepting orders?',
    ACCEPT: 'Accept',
    ACCOUNT: 'Account',
    ADD_CUS_SELLER: 'Is seller not listed below? Add your favorite seller',
    ADD_ITEM: 'Add Item',
    ADD_NEW: 'ADD NEW',
    ADD_TO_CART: 'Add',
    ADDRESS_INFO: 'Address Information',
    ADD_PAYMENT: 'Add Payment',
    ADDRESS_ONE: 'Address One',
    ADDRESS_TWO: 'Address Two',
    ADDRESS_UPDATE_SUCCESS: 'Address is updated successfully',
    ADDRESS: 'Address',
    AGE: 'Age',
    ALL_PRICE_NOT_PROVIDED:
      'Please provede price for all the items before proceeding',
    ALTERNET_ORDER_TEXT:
      'Do you want to suggest an alternate item for the order?',
    AMOUNT: 'Amount',
    ANY_SELLER: 'Any Seller',
    APP_TITLE: 'ReO',
    ASK_CREDIT: 'Credit Book',
    AT: 'at',
    ATTEMPT_LEFT: 'You have x attempts left',
    AVL_ROLES: 'Available Roles',
    BRAND: 'Brand',
    BUSINESS_INFO: 'Business Information',
    BUYER_INFO: 'Customer Information',
    BUYER_NAME: 'Customer Name',
    CANCEL_ORDER_MESSAGE: 'Are you sure you want to cancel this order?',
    CANCEL: 'Cancel',
    CANT_FETCH_YOUR_LOCATION:
      "Can't fetch your location, please enable your location from setting ",
    CANT_FIND_ITEM_MODAL: 'Add new product',
    CANT_FIND_ITEM: 'Add your own item',
    CASH_ON_DELIVERY: 'Cash on delivery',
    CAT_INFO: 'Category Information',
    CATALOG: 'Catalog',
    CHANGE_PASSWORD: 'Change Password',
    CHANGE: 'Change',
    CITY: 'City',
    CONF_PASSWORD: 'Confirm Password',
    CONTACT_NUMBER: 'Contact Number',
    CONTINUE_SHOPPING: 'Continue Shopping',
    COUNTRY: 'Country',
    CREDIT: 'Credit',
    DATE: 'Date',
    DEFAULT_ADD: 'Default Address',
    DEFAULT_IMAGE_URL:
      'https://objectstorage.ap-seoul-1.oraclecloud.com/n/cnw3sskzhygt/b/littlekirana/o/ImageComingSoon.png',
    DEL_DIST: 'How far do you want to deliver (in km)?',
    DELIVER: 'Home Delivery',
    DELIVERY_ADDRESS: 'Delivery Addresses',
    DELIVERY_CHARGES: 'Delivery Charges',
    DELIVERY_INFO: 'Delivery Info',
    DELIVERY_LOCATION: 'Delivery Location',
    DELIVERY_TIME: 'Delivery Time',
    DISCOUNT: 'Discount',
    DISTANCE: 'Distance',
    DISTANCE_UNIT: 'Km',
    DRAWER_ABOUT: 'About Us',
    DRAWER_HOME: 'Home',
    DRAWER_LOG_OUT: 'Log Out',
    DRAWER_NEW_ROLE: 'Register for New Role',
    DRAWER_PRIVACY: 'Terms & Conditions',
    DRAWER_SHARE: 'Invite Friends',
    EMPTY_CART: 'Your cart seems to be empty. Start shopping',
    EMAIL: 'Email ID',
    FEEDBACK_TYPE: 'Feedback Type',
    FIRST_NAME: 'First Name',
    FORGOT_PASSWORD: 'Forgot Password',
    GIVE_FEEDBACK: 'Give your feedback here',
    HEAD_ADD_ADDRESS: 'Add Address',
    HEAD_CART: 'My Cart',
    HEAD_CONFIRM: 'Confirm Update',
    HEAD_CONTACT_US: 'Contact Us',
    HEAD_FORGOT_PASSWORD: 'Forgot Password',
    HEAD_LEDGER_MONTH: 'Credit Book (Monthly)',
    HEAD_LEDGER: 'Credit Book',
    HEAD_NOTIFICATION: 'Important Updates',
    HEAD_ORDERS: 'My Orders',
    HEAD_OTP: 'OTP',
    HEAD_PRODUCT_CAT: 'Product Catalog',
    HEAD_PROFILE_UPDATE: 'Edit Profile',
    HEAD_RESET_PASSWORD: 'Reset Password',
    HEAD_SEARCH_PRODUCT: 'Products',
    HEAD_SELECT_SELLER: 'Select Seller',
    HEAD_SIGN_UP: 'Register Yourself',
    CREDIT_AVAILABLE: 'Credit Transaction available',
    I_ACCEPT: 'I accept ',
    INFO_SAVE: 'Press Save button to update',
    INVALID_PIN: 'Invalid PIN code',
    IS_PRODUCT_IN_REGIONAL: 'Is this product in regional language',
    IS_SELL: 'Sell?',
    ITEM_NAME: 'Item Name',
    ITEM_PURCHASED: 'Item Purchased',
    ITEM: 'Item(s)',
    LANGUAGE: 'Language',
    LAST_ITEM:
      'You cannot remove this item as this is the last item in the order. Please cancel the order',
    LAST_NAME: 'Last Name',
    LOGIN: 'Login',
    LOGOUT_MESSAGE:
      'Are you sure you want to log out? Please note that your cart will be empty if there is any item',
    LOGOUT: 'Log Out',
    MARK_COMPLETE: 'Delivered',
    MOBILE_NO: 'Mobile/Phone Number',
    MOD: 'Added/Updated',
    MONTH: 'Month',
    MORE_10_ITEMS: 'You cannot add more that 10 items',
    NA: 'N/A',
    NAME: 'Name',
    NEED_HELP: 'Do you do home delivery?',
    NEXT: 'Next',
    NO_ADDRESS: 'You need to add atleast one delivery address',
    NO_DATA: 'No data is found',
    NO_SELLER: 'No seller matches your search criteria',
    NO_NOTIFICATION: 'No notification is available',
    NO: 'No',
    NOT_AVAILABLE: 'Currently This Feature Is Not Available.',
    NUMBER_OF_ITEMS: 'Number of Items',
    OK: 'OK',
    OLD_NEW_SAME: 'You can not use your old password',
    OLD_PASSWORD: 'Old Password',
    ORDER_DEILIVERY_MESSAGE: 'Have you delivered this order?',
    ORDER_DEL_CONF:
      'Have you recieved order # ! from @ which you have ordered on $?',
    ORDER_DETAILS: 'Order Details',
    ORDER_ID: 'Order ID',
    ORDER_NOW: 'Place Order',
    ORDER_SUMMARY: 'Order Summary',
    ORDER_SUBMIT_TIME: 'Order Submtted Time',
    PAGE_SIZE: 70,
    PASSWORD_POLICY:
      'Password must contain at least 6 charaecters with no whitespace',
    PASSWORD: 'Password',
    PASSWORD_SUCCESS: 'Password is changed successfully',
    PAYMENT_DETAILS: 'Payment Details',
    PAYMENT_INFO: 'Payment Info',
    PAYMENT_MODE: 'Payment Mode',
    PERSONAL_INFO: 'Personal Information',
    PHONE_CONTACTS: 'Phone Contacts',
    PICK_UP: 'Store Pickup',
    PINCODE: 'Pincode',
    PLACED_ON: 'Placed On',
    PLACEHOLDER_HEIGHT: 'Height(cm)',
    PLACEHOLDER_WEIGHT: 'Weight(Kg)',
    PLACEHOLDER_FOOD: 'Food Habbit',
    PLACEHOLDER_LANG: 'Languages',
    PLEASE_SELECT: 'Please Select',
    POINTS: 'Points - #',
    PRICE_PER_UNIT: 'Price/Unit',
    PRICE: 'Price',
    PRODUCT_NAME: 'Product Name',
    PRODUCT: 'Product',
    PROFILE: 'Profile',
    PROMOCODE: 'Promo Code',
    PSWD_POLICY: 'Password Policy',
    QUANTITY: 'Quantity',
    RE_ORDER: 'Re-Order',
    REFF_CODE: 'Referral Code:',
    REFF_CONT_HEAD: 'Referred Contacts',
    REFF_HEADER: '♥ # earned',
    REFF_SUB: 'For referring # friends',
    REFF_TEXT:
      'I want to share this great shopping app with you. I use it for everyday grocery shopping from my smart phone and I think you’d like it too. Here’s the link <URL to Playstore>/#, if you want to give it a try',
    REG_FAILED: 'Registration Failed',
    REG_SUCCESS: 'Rigistration Successful',
    REGISTERED_ADDRESS: 'Registered Address',
    REM: 'Removed',
    REMOVE_NOT_POSSIBLE: 'You have already removed this item',
    REMOVE: 'Remove',
    REMOVE_USER: 'Suspend From Buying In Credit',
    ROLE: 'Role',
    SEARCH_CAT: 'Search Category',
    SEARCH_IN: 'Search in',
    SEARCH_PRODUCT: 'Search Product',
    SEARCH_SELLER: 'Seller Name/Mobile',
    SEARCH: 'Search',
    SELECT_SEARCH_LANGUAGE: 'Language',
    SELECT: 'Select',
    SELLER_CAT_NO: 13,
    SELLER_INFO: 'Seller Information',
    SELLER_NAME: 'Seller Name',
    SELLER_PHONE: 'Seller Phone Number',
    SELLER_ADDRESS: 'Seller Address',
    SET_AS_DEFAULT: 'Set this as default address',
    SET_SELLER_SUCCESS: 'Seller is set successfully',
    SET_THIS_ADDRESS_AS_DEFAULT_ADDRESS: 'Set this as default address',
    SHOP_NAME: 'Shop Name',
    SIGN_UP: 'Create Account',
    STANDARD_QUANTITY: 'Measurement',
    STATE: 'State',
    STATUS: 'Status',
    STORE_CHANGE: 'Change Store',
    STORE_SELECT: 'Select Store',
    SUBMIT_OTP: 'Submit OTP',
    SUBMIT: 'Submit',
    SUGGEST_ALTERNATE: 'Alternate',
    TAB_CANCELLED: 'CANCELLED',
    TAB_EXECUTED: 'COMPLETED',
    TAB_PENDING: 'PENDING',
    TERMS_AND_CONDITIONS: 'Terms and Conditions ',
    THANK_YOU: 'Thank You!',
    TNC: 'Placeholder for Terms & Conditions',
    TOT_QUANTITY: 'Total',
    TOTAL_AMOUNT: 'Total Amount',
    TOTAL_PAID: 'Paid',
    TOTAL_PENDING: 'Ordered',
    TOTAL: 'Sub Total:',
    UNIT_OF_MEASURE: 'In',
    UNIT: 'Unit',
    UPDATE: 'Update',
    USE_MY_LOCATION: 'Use My Location',
    USER_DETAILS: 'User Details',
    VIEW_CART: 'View Cart',
    YES: 'Yes',
    YOU_DONT_SELL: 'Other Product(s)',
    YOU_MUST_ACCEPT_TERMS_AND_CONDITION_BEFORE_SIGNUP:
      'You must accept terms and condition before signup',
    YOU_SELL: 'Your Product(s)',
  });
  