import {StyleSheet, Dimensions} from 'react-native';
import {dynamicSize, getFontSize} from './responsive';
import colors from '../components/colors';
const {height, width} = Dimensions.get('window');
export const primaryColor = colors.purple;
export const primaryBackgroundColor = colors.smoke;
export const secondaryColor = colors.white;
export const cardBackgroundColor = colors.white;
export const removedOrderColor = colors.badRed;
export const newOrderColor = colors.goodGreen;
export const inactiveColor = colors.darkGrey;
export const colorRed = colors.red;
export const colorGreen = colors.green;
export const drawerWidth = width - dynamicSize(100);
export const commonTextSize = getFontSize(14);
const infoTextSize = getFontSize(11);
const drawerHeaderTextSize = getFontSize(18);
const drawerItemTextSize = getFontSize(16);
const headerTextSize = getFontSize(18);
const fontNormal = 'Roboto-Regular';
const fontBold = 'Roboto-Medium';
const fontItalic = 'Roboto-MediumItalic';
export default (commonStyle = StyleSheet.create({
  loginCard: {
    elevation: 5,
    shadowColor: colors.shadow,
    shadowOpacity: 1,
    shadowRadius: 30,
    shadowOffset: {width: dynamicSize(5), height: dynamicSize(5)},
    paddingHorizontal: dynamicSize(20),
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    width: width - dynamicSize(30),
    alignSelf: 'center',
    padding: dynamicSize(10),
    borderRadius: dynamicSize(25),
    marginBottom: dynamicSize(15),
  },
  inputView: {
    backgroundColor: primaryBackgroundColor,
    marginHorizontal: dynamicSize(36),
    width: width - dynamicSize(50),
    justifyContent: 'center',
    alignSelf: 'center',
  },
  linkText: {
    color: primaryColor,
    fontSize: commonTextSize,
    padding: dynamicSize(5),
    //fontWeight: 'bold',
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
    textDecorationColor: primaryColor,
    fontFamily: fontBold,
  },
  errorText: {
    fontSize: infoTextSize,
    color: colors.red,
  },
  navCommonTabIcon: {
    width: dynamicSize(26),
    height: dynamicSize(26),
  },
  navRemoveShadow: {
    borderBottomColor: null,
    shadowColor: null,
    elevation: 0,
    shadowRadius: 0,
    borderBottomWidth: 0,
    shadowOpacity: 0,
    shadowOffset: {width: dynamicSize(0), height: dynamicSize(0)},
  },
  profileInfoContainer: {
    height: dynamicSize(80),
    alignItems: 'center',
    width: width - dynamicSize(100),
    justifyContent: 'center',
    borderBottomWidth: 1.5,
    flexDirection: 'row',
    borderBottomColor: primaryColor,
    backgroundColor: primaryColor,
  },
  profileImageContainer: {
    borderWidth: 1,
    marginHorizontal: dynamicSize(15),
    borderColor: secondaryColor,
    height: dynamicSize(60),
    width: dynamicSize(60),
    borderRadius: dynamicSize(30),
    alignItems: 'center',
    justifyContent: 'center',
  },
  navName: {
    textAlign: 'left',
    color: secondaryColor,
    //fontStyle: 'italic',
    fontSize: drawerHeaderTextSize,
  },

  drawerTileContainer: {
    height: dynamicSize(40),
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: width - dynamicSize(100),
    flexDirection: 'row',
    backgroundColor: secondaryColor,
    //borderBottomWidth: 1.5,
    //borderBottomColor: primaryColor,
  },
  fullWidth: {
    width: width,
  },
  drawerTileIcon: {
    marginHorizontal: dynamicSize(15),
    tintColor: primaryColor,
  },
  drawerTileText: {
    color: primaryColor,
    fontSize: drawerItemTextSize,
    //fontWeight: 'bold',
  },
  appHeaderContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    width,
    backgroundColor: primaryColor,
    height: dynamicSize(55),
    borderBottomColor: '#C7C7CD',
    shadowColor: '#bcbcbc',
    elevation: 8,
    shadowRadius: 5,
    borderBottomWidth: 0.5,
    shadowOpacity: 0.5,
    shadowOffset: {width: dynamicSize(5), height: dynamicSize(5)},
  },
  appHeaderContainerGrad: {
    alignItems: 'center',
    flexDirection: 'row',
    width,
    height: dynamicSize(110),
    borderBottomColor: '#C7C7CD',
    shadowColor: '#bcbcbc',
    elevation: 8,
    shadowRadius: 5,
    borderBottomWidth: 0.5,
    shadowOpacity: 0.5,
    shadowOffset: {width: dynamicSize(5), height: dynamicSize(5)},
  },
  appHeaderContainerGradSeller: {
    alignItems: 'center',
    flexDirection: 'row',
    width,
    height: dynamicSize(55),
    borderBottomColor: '#C7C7CD',
    shadowColor: '#bcbcbc',
    elevation: 8,
    shadowRadius: 5,
    borderBottomWidth: 0.5,
    shadowOpacity: 0.5,
    shadowOffset: {width: dynamicSize(5), height: dynamicSize(5)},
  },
  appHeaderNameStyleGrad: {
    color: secondaryColor,
    fontSize: commonTextSize,
    left: dynamicSize(55),
    //fontWeight: 'bold',
  },
  appHeaderLeftView: {
    justifyContent: 'center',
    alignItems: 'center',
    width: dynamicSize(50),
    height: dynamicSize(50),
  },
  appHeaderIconStyle: {
    tintColor: secondaryColor,
  },
  appHeaderNameStyle: {
    color: secondaryColor,
    fontSize: headerTextSize,
    left: dynamicSize(55),
    //fontWeight: 'bold',
  },
  mainContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: primaryBackgroundColor,
    paddingVertical: dynamicSize(10),
    width,
    //borderRadius: 5,
  },
  container: {
    alignItems: 'center',
    paddingVertical: dynamicSize(10),
    flex: 1,
    width,
  },
  containerNoPadding: {
    alignItems: 'center',
    //paddingVertical: dynamicSize(10),
    flex: 1,
    width,
  },
  halfContainer: {
    alignItems: 'center',
    paddingVertical: dynamicSize(3),
    flex: 1,
    width: width / 2,
    borderWidth: dynamicSize(1.5),
    borderColor: primaryColor,
    margin: dynamicSize(5),
    backgroundColor: cardBackgroundColor,
  },
  keyboardContainer: {
    alignItems: 'center',
    paddingHorizontal: dynamicSize(25),
  },
  keyboardContainerNoPadding: {
    alignItems: 'center',
    //paddingHorizontal: dynamicSize(25),
  },

  footerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: dynamicSize(10),
    paddingVertical: dynamicSize(5),
    width,
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: primaryColor,
  },
  primaryColor: {
    color: primaryColor,
  },
  secondaryColor: {
    color: secondaryColor,
  },
  imageTheme: {
    tintColor: primaryColor,
  },
  inverseImageTheme: {
    tintColor: secondaryColor,
  },
  row: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignSelf: 'center',
  },
  prodInfoText: {
    fontSize: infoTextSize,
    color: colors.darkGrey,
    //fontWeight: 'bold',
  },
  commonText: {
    //fontWeight: 'normal',
    color: colors.black,
    fontSize: commonTextSize,
    textAlign: 'left',
    fontFamily: fontNormal,
  },
  commonTextChange: {
    //fontWeight: 'normal',
    color: colors.black,
    fontSize: commonTextSize,
    textAlign: 'left',
    fontFamily: 'IndieFlower-Regular',
  },
  italicText: {
    //fontWeight: 'normal',
    color: colors.black,
    fontSize: commonTextSize,
    textAlign: 'left',
    fontFamily: fontItalic,
  },
  boldText: {
    color: colors.black,
    fontSize: commonTextSize,
    textAlign: 'left',
    //fontWeight: 'bold',
    fontFamily: fontBold,
  },
  loginInputText: {
    color: colors.black,
    fontSize: drawerItemTextSize,
    textAlign: 'left',
    //fontWeight: 'bold',
    fontFamily: fontBold,
  },
  inverseCommonText: {
    //fontWeight: 'normal',
    color: colors.white,
    fontSize: commonTextSize,
    textAlign: 'left',
    fontFamily: fontNormal,
  },
  inverseBoldText: {
    color: colors.white,
    fontSize: commonTextSize,
    textAlign: 'left',
    //fontWeight: 'bold',
    fontFamily: fontBold,
  },
  buttonContainer: {
    elevation: 5,
    shadowColor: colors.shadow,
    shadowOpacity: 1,
    shadowRadius: 30,
    shadowOffset: {width: dynamicSize(5), height: dynamicSize(5)},
    paddingHorizontal: dynamicSize(20),
    borderRadius: dynamicSize(20),
    height: dynamicSize(30),
    backgroundColor: primaryColor,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: dynamicSize(2),
    marginHorizontal: dynamicSize(2),
  },
  buttonModalContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingTop: dynamicSize(10),
  },
  buttonText: {
    fontSize: commonTextSize,
    color: secondaryColor,
    //fontWeight: 'bold',
    textAlign: 'center',
  },
  orderTitle: {
    paddingBottom: dynamicSize(3),
    //fontWeight: 'bold',
    fontSize: drawerItemTextSize,
  },
  orderScrollContainer: {
    width,
    alignItems: 'center',
    marginVertical: dynamicSize(5),
  },
  orderDetailsContainer: {
    flex: 1,
    marginBottom: dynamicSize(5),
  },
  productCard: {
    justifyContent: 'space-between',
    paddingHorizontal: dynamicSize(0),
    width: '46%',
    alignItems: 'flex-start',
    paddingVertical: dynamicSize(0),
  },
  productCardSeparator: {
    flex: 1,
    height: dynamicSize(10),
  },
  flatListContainer: {
    paddingVertical: dynamicSize(10),
  },
  addToCartContainer: {
    paddingHorizontal: dynamicSize(15),
    backgroundColor: primaryColor,
    borderRadius: dynamicSize(5),
    paddingVertical: dynamicSize(5),
    elevation: 8,
    shadowColor: colors.shadow,
    shadowOpacity: 1,
    shadowRadius: 30,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: {width: dynamicSize(5), height: dynamicSize(5)},
    marginVertical: dynamicSize(5),
    marginHorizontal: dynamicSize(5),
  },
  cardHolderContainer: {
    paddingVertical: dynamicSize(5),
    flex: 1,
    alignSelf: 'center',
    width: width - dynamicSize(15),
  },
  cardHeaderText: {
    color: colors.black,
    //fontWeight: 'bold',
    fontSize: commonTextSize,
    textAlign: 'left',
  },
  cardContainer: {
    paddingHorizontal: dynamicSize(5),
    paddingVertical: dynamicSize(10),
    borderRadius: dynamicSize(5),
    width: width - dynamicSize(15),
    elevation: 8,
    backgroundColor: cardBackgroundColor,
    shadowColor: colors.shadow,
    shadowOpacity: 1,
    shadowRadius: 30,
    shadowOffset: {width: dynamicSize(5), height: dynamicSize(5)},
    marginTop: dynamicSize(5),
  },
  cardRowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardColumnContainer: {
    alignItems: 'flex-start',
    paddingLeft: dynamicSize(5),
  },
  cardRowDataContainer: {
    flex: 1,
    alignItems: 'flex-start',
    paddingVertical: dynamicSize(4),
    justifyContent: 'flex-start',
  },
  cardRowCenterContainer: {
    flex: 0.02,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingVertical: dynamicSize(5),
    paddingHorizontal: dynamicSize(7),
  },
  spaceBetweenCard: {
    flex: 1,
    justifyContent: 'space-evenly',
  },
  tableHeader: {
    backgroundColor: primaryColor,
    flexDirection: 'row',
    paddingHorizontal: dynamicSize(2),
    width: width - dynamicSize(15),
    borderWidth: 0.5,
    //fontFamily: 'IndieFlower-Regular',
    //borderTopLeftRadius: dynamicSize(11),
    //borderRadius: dynamicSize(11),
  },
  halfTableHeader: {
    backgroundColor: primaryColor,
    flexDirection: 'row',
    paddingVertical: dynamicSize(2),
    width: (width - dynamicSize(40)) / 2,
  },
  tableHeaderWoBorder: {
    backgroundColor: primaryColor,
    flexDirection: 'row',
    paddingVertical: dynamicSize(2),
    width: width - dynamicSize(15),
  },
  tableheaderText: {
    color: secondaryColor,
    //fontWeight: 'bold',
    fontSize: commonTextSize,
    alignSelf: 'center',
    fontFamily: 'DynaPuff-Medium',
  },
  singleCell: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
    padding: dynamicSize(5),
  },
  searchContainer: {
    marginVertical: dynamicSize(10),
    borderRadius: dynamicSize(22),
    flexDirection: 'row',
    width: width - dynamicSize(30),
    height: dynamicSize(44),
    borderColor: primaryColor,
    borderWidth: 2,
    backgroundColor: colors.white,
    paddingHorizontal: dynamicSize(10),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  searchTextInput: {
    flex: 1,
    fontSize: commonTextSize,
    //fontWeight: 'bold',
    borderRadius: dynamicSize(25),
    fontFamily: fontBold,
  },
  recentSearchIcon: {
    tintColor: colors.lightGrey,
  },
  searchResult: {
    paddingVertical: dynamicSize(5),
    paddingHorizontal: dynamicSize(10),
    width,
    backgroundColor: cardBackgroundColor,
    height: dynamicSize(40),
    flexDirection: 'row',
  },
  seperator: {
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGrey,
  },
  searchImageContainer: {
    flex: 0.2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchTextContainer: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  buttonHalf: {
    marginVertical: dynamicSize(5),
    width: width / 2,
    alignSelf: 'center',
  },
  buttonThird: {
    marginVertical: dynamicSize(5),
    width: width / 3,
    alignSelf: 'center',
  },
  buttonQuar: {
    marginVertical: dynamicSize(5),
    width: (width * 5) / 16,
    alignSelf: 'center',
  },
  subHeaderContainer: {
    backgroundColor: cardBackgroundColor,
    paddingHorizontal: dynamicSize(7.5),
    paddingVertical: dynamicSize(10),
    flexDirection: 'row',
    alignItems: 'flex-start',
    width,
    marginBottom: dynamicSize(10),
    borderBottomWidth: 1,
    borderBottomColor: primaryColor,
    alignSelf: 'center',
  },
  leftIconStyle: {
    marginRight: dynamicSize(10),
    tintColor: primaryColor,
    height: dynamicSize(25),
    width: dynamicSize(25),
  },
  rightIconStyle: {
    marginLeft: dynamicSize(10),
    tintColor: primaryColor,
    height: dynamicSize(25),
    width: dynamicSize(25),
  },
  counterView: {
    alignSelf: 'center',
    marginHorizontal: dynamicSize(5),
    width: dynamicSize(110),
    height: dynamicSize(30),
    borderRadius: dynamicSize(15),
    flexDirection: 'row',
  },
  minusView: {
    flex: 1,
    borderBottomLeftRadius: dynamicSize(5),
    borderTopLeftRadius: dynamicSize(5),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colorRed,
    borderRadius: dynamicSize(15),
  },
  plusView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopRightRadius: dynamicSize(7),
    borderBottomRightRadius: dynamicSize(7),
    backgroundColor: colorGreen,
    borderRadius: dynamicSize(15),
  },
  paginationView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: primaryColor,
    borderRadius: dynamicSize(15),
  },
  invPaginationView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: secondaryColor,
    borderRadius: dynamicSize(15),
  },
  modalContainer: {
    padding: dynamicSize(20),
    borderRadius: dynamicSize(5),
    backgroundColor: primaryBackgroundColor,
    width: width - dynamicSize(50),
    maxHeight: height - dynamicSize(50),
  },
  maxHeight: {
    height: height - dynamicSize(75),
  },
  modalFlatListContainer: {
    height: width,
    flexGrow: 0,
    width: width - dynamicSize(90),
  },
  modalTableHeader: {
    backgroundColor: primaryColor,
    flexDirection: 'row',
    paddingVertical: dynamicSize(2),
    width: width - dynamicSize(90),
  },
  modalRowLabelContainer: {
    width: (width - dynamicSize(50)) * 0.3,
    alignItems: 'flex-start',
    paddingVertical: dynamicSize(4),
    justifyContent: 'center',
  },
  modalRowCenterContainer: {
    width: (width - dynamicSize(50)) * 0.02,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: dynamicSize(4),
  },
  modalRowValueContainer: {
    width: (width - dynamicSize(50)) * 0.6,
    alignItems: 'flex-start',
    paddingVertical: dynamicSize(4),
    justifyContent: 'center',
  },
  modalAddNew: {
    width: (width - dynamicSize(85)) / 2,
    marginVertical: dynamicSize(15),
    marginHorizontal: dynamicSize(5),
    marginTop: dynamicSize(20),
  },
  dropDownContainer: {
    width: width - dynamicSize(50),
  },
  bottomShadow: {
    backgroundColor: '#fff',
    borderTopColor: '#C7C7CD',
    shadowColor: '#d6d4d4',
    borderTopWidth: Platform.OS === 'ios' ? 1 : 0,
    elevation: 8,
    shadowOpacity: 1,
    shadowRadius: 30,
    shadowOffset: {width: dynamicSize(0), height: dynamicSize(-20)},
  },
  roundContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: width / 3 + dynamicSize(10),
    height: width / 3 + dynamicSize(10),
    borderRadius: dynamicSize(width / 3 + dynamicSize(10) / 2),
  },
  rowContainer: {
    width,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  addressComponent: {
    marginVertical: dynamicSize(10),
    paddingHorizontal: dynamicSize(7.5),
  },
  pickerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: dynamicSize(40),
    width: width / 2 - dynamicSize(40),
    borderColor: primaryColor,
    borderRadius: dynamicSize(20),
    borderWidth: 1,
    marginHorizontal: dynamicSize(15),
  },
  pickerIcons: {
    marginHorizontal: dynamicSize(15),
    width: dynamicSize(25),
    height: dynamicSize(25),
    tintColor: primaryColor,
  },
  radioIcon: {
    width: dynamicSize(17),
    height: dynamicSize(17),
  },
  defaultItemSeperator: {
    height: dynamicSize(13),
  },
  messageContainer: {
    backgroundColor: cardBackgroundColor,
    borderRadius: dynamicSize(5),
    width: width - dynamicSize(15),
    padding: dynamicSize(10),
    borderWidth: 1,
    borderColor: primaryColor,
  },
  viewWithBorder: {
    backgroundColor: cardBackgroundColor,
    marginBottom: dynamicSize(10),
    padding: dynamicSize(10),
    width: width - dynamicSize(15),
    alignSelf: 'center',
    borderColor: primaryColor,
    borderWidth: 1,
    borderRadius: dynamicSize(5),
  },
  invViewWithBorder: {
    backgroundColor: primaryColor,
    marginBottom: dynamicSize(10),
    padding: dynamicSize(10),
    width: width - dynamicSize(15),
    alignSelf: 'center',
    borderColor: cardBackgroundColor,
    borderWidth: 1,
    borderRadius: dynamicSize(5),
  },
  imageContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    padding: dynamicSize(5),
  },
  imageLabel: {
    fontSize: commonTextSize,
    marginLeft: 10,
  },
  optContainer: {
    width: dynamicSize(42),
    paddingHorizontal: dynamicSize(10),
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: inactiveColor,
  },
  otpTextStyle: {
    color: primaryColor,
    fontSize: getFontSize(19),
    fontFamily: fontBold,
    //fontWeight: 'bold',
  },
  pageTab: {
    backgroundColor: primaryColor,
    flexDirection: 'row',
    paddingTop: dynamicSize(2),
    width: width,
  },
  pageTabText: {
    color: secondaryColor,
    fontSize: commonTextSize,
    fontFamily: 'FredokaOne-Regular',
  },
  homeHeaderContainer: {
    //backgroundColor: cardBackgroundColor,
    flexDirection: 'row',
    paddingBottom: dynamicSize(10),
    width: width,
    marginBottom: dynamicSize(5),
    borderBottomWidth: 1,
    borderBottomColor: primaryColor,
  },
  counterText: {
    color: primaryColor,
    fontSize: getFontSize(21),
    textAlign: 'center',
    //fontWeight: 'bold',
  },
  deliveryContainer: {flexDirection: 'row', padding: dynamicSize(10)},
  redIcon: {
    tintColor: colors.red,
  },
  greenIcon: {
    tintColor: colors.green,
  },
  redtext: {
    color: colors.red,
  },
  greenText: {
    color: colors.green,
  },
  primaryIcon: {
    tintColor: primaryColor,
  },
  orderDetailsImage: {
    alignSelf: 'center',
    width: dynamicSize(60),
    height: dynamicSize(60),
  },
  viewWithBorderOrder: {
    backgroundColor: cardBackgroundColor,
    marginBottom: dynamicSize(2),
    paddingVertical: dynamicSize(5),
    paddingHorizontal: dynamicSize(8),
    width: width - dynamicSize(15),
    alignSelf: 'center',
    borderColor: '#fff',
    borderWidth: 0.5,
    borderRadius: dynamicSize(11),
  },
  viewInvWithBorderOrder: {
    backgroundColor: cardBackgroundColor,
    marginTop: dynamicSize(5),
    padding: dynamicSize(8),
    width: width - dynamicSize(15),
    alignSelf: 'center',
    borderColor: primaryColor,
    borderWidth: 0.5,
    borderRadius: dynamicSize(11),
  },
  priceTotalText: {
    color: primaryColor,
    fontSize: drawerItemTextSize,
    //fontWeight: 'bold',
    alignSelf: 'flex-start',
  },
  imageThemeGreen: {
    tintColor: colorGreen,
  },
  imageThemeDarkGrey: {
    tintColor: colors.darkGrey,
  },
  contactImage: {
    alignSelf: 'flex-start',
    width: dynamicSize(35),
    height: dynamicSize(35),
    borderRadius: dynamicSize(15),
  },
  contactCard: {
    //backgroundColor: cardBackgroundColor,
    marginBottom: dynamicSize(2),
    paddingVertical: dynamicSize(8),
    paddingHorizontal: dynamicSize(8),
    width: width - dynamicSize(15),
    alignSelf: 'center',
    //borderColor: primaryColor,
    //borderWidth: 0.5,
    borderRadius: dynamicSize(11),
  },
  marginBottom25: {marginBottom: dynamicSize(25)},
  viewInvWithBorderOrderModal: {
    backgroundColor: cardBackgroundColor,
    marginTop: dynamicSize(5),
    padding: dynamicSize(8),
    width: width - dynamicSize(90),
    alignSelf: 'center',
    borderColor: primaryColor,
    borderWidth: 1,
    borderRadius: dynamicSize(11),
  },
  banner: {
    height: width / 5,
    width,
    backgroundColor: primaryColor,
    justifyContent: 'center',
    paddingHorizontal: dynamicSize(15),
  },
  bannerTextBig: {
    textAlign: 'left',
    color: secondaryColor,
    fontSize: getFontSize(23),
    //fontWeight: 'bold',
  },
  bannerTextSmall: {
    textAlign: 'left',
    color: secondaryColor,
    //fontStyle: 'italic',
    fontSize: commonTextSize,
    //alignSelf: 'center',
  },
  refferCard: {
    marginBottom: dynamicSize(2),
    paddingVertical: dynamicSize(8),
    paddingHorizontal: dynamicSize(8),
    width: width - dynamicSize(15),
    alignSelf: 'center',
    height: dynamicSize(70),
  },
  refferPointText: {
    fontSize: commonTextSize,
    textAlign: 'center',
  },
  categoryCheckContainer: {
    height: dynamicSize(40),
    alignItems: 'flex-start',
    width: (width - dynamicSize(50)) / 2,
  },
  splashButtonContainer: {
    elevation: 5,
    shadowColor: colors.shadow,
    shadowOpacity: 1,
    shadowRadius: 30,
    shadowOffset: {width: dynamicSize(5), height: dynamicSize(5)},
    paddingHorizontal: dynamicSize(20),
    borderRadius: dynamicSize(25),
    height: dynamicSize(50),
    backgroundColor: primaryColor,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: dynamicSize(2),
    marginHorizontal: dynamicSize(2),
    borderWidth: dynamicSize(2),
    borderColor: secondaryColor,
    width: width - dynamicSize(30),
    marginBottom: dynamicSize(20),
    alignSelf: 'center',
  },
  splashButtonText: {
    fontSize: getFontSize(22),
    color: secondaryColor,
    //fontWeight: 'bold',
    textAlign: 'center',
  },
  textMultiContainer: {
    marginHorizontal: dynamicSize(20),
    marginTop: dynamicSize(20),
    height: dynamicSize(200),
    backgroundColor: cardBackgroundColor,
    width: width - dynamicSize(50),
    borderWidth: dynamicSize(2),
    fontFamily: fontBold,
    fontSize: commonTextSize,
  },
  textErrorContainer: {
    marginBottom: dynamicSize(20),
    width: width - dynamicSize(50),
    alignSelf: 'center',
  },
  viewNotofication: {
    //backgroundColor: cardBackgroundColor,
    marginBottom: dynamicSize(10),
    paddingVertical: dynamicSize(10),
    paddingHorizontal: dynamicSize(10),
    width: width,
    alignSelf: 'center',
    borderColor: primaryColor,
    borderBottomWidth: dynamicSize(1),
    //borderWidth: 0.5,
    //borderRadius: dynamicSize(11),
  },
}));
