import { StyleSheet, Dimensions } from 'react-native';
import {
    responsiveHeight,
    responsiveWidth,
    responsiveFontSize
} from "react-native-responsive-dimensions";

import colors from './colors';

const widthIcon = Dimensions.get('window').width / 2;
const heightHomeUpperContent = Dimensions.get('window').height / 14;
const widthCard = Dimensions.get('window').width;

const { width, height } = Dimensions.get('screen');

export default globalStyles = StyleSheet.create({
    card: {
        //height: 225,
        backgroundColor: colors.white,
        // width: totalWidth / 5,
        width: responsiveWidth(25),
        marginHorizontal: 5,
        borderRadius: 30,
        // borderBottomEndRadius: 50,
        // borderBottomLeftRadius: 25,
        // borderBottomRightRadius: 25,
        marginBottom: 2,
        paddingTop: 5,
        // paddingHorizontal: 30,
        // padding: 15,
        shadowColor: colors.black,
        elevation: 1,
    },
    icon: {
        flex: 1,
        //width,
        width: responsiveWidth(20),
        resizeMode: "contain",
    },
    cardPopular: {
        // height: 160,
        // flex: 1,
        height: responsiveHeight(30),
        backgroundColor: colors.white,
        // width: widthPopular,
        width: responsiveWidth(40),
        marginHorizontal: 5,
        borderRadius: 5,
        // borderBottomEndRadius: 50,
        // borderBottomLeftRadius: 25,
        // borderBottomRightRadius: 25,
        // marginBottom: 2,
        // paddingTop: 5,
        // paddingHorizontal: 30,
        padding: 15,
        // shadowColor: colors.black,
        elevation: 10,
        //marginVertical: responsiveWidth(1),
        // alignItems:'center',
        // justifyContent:'center'
        //flexDirection: 'row',
    },
    ordercard: {
        // height: 85,
        backgroundColor: colors.lightGreyWhite,
        // width: widthIcon,
        marginHorizontal: 10,
        borderRadius: 10,
        // borderBottomEndRadius: 50,
        // borderBottomLeftRadius: 25,
        // borderBottomRightRadius: 25,
        marginBottom: 10,
        padding: 10,
        // paddingHorizontal: 30,
        // padding: 15,
        // alignItems: "flex-start",
        // justifyContent: "flex-start",
        flex: 1,
        elevation: 1,
        shadowColor: colors.black,
    },
    cardWithImage: {
        // height: 85,
        backgroundColor: colors.lightGreyWhite,
        // width: widthIcon,
        //marginHorizontal: 10,
        borderRadius: 10,
        // borderBottomEndRadius: 50,
        // borderBottomLeftRadius: 25,
        // borderBottomRightRadius: 25,
        marginBottom: 5,
        paddingTop: 5,
        // paddingHorizontal: 30,
        // padding: 15,
        // alignItems: "flex-start",
        // justifyContent: "flex-start",
        flex: 1,
        elevation: 1,
        shadowColor: colors.black,
    },
    iconItem: {
        // flex: 0.5,
        width: widthIcon,
        height: responsiveHeight(10),
        resizeMode: "contain",
        alignItems: 'center',
        justifyContent: 'center',
        // backgroundColor: colors.lightGreyWhite,
    },
    searchContainer: {
        height: responsiveHeight(6),
        width: responsiveWidth(85),
        backgroundColor: colors.lightGreyWhite,
        borderRadius: 5,
        //flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        elevation: 10,
        shadowColor: colors.black,
    },
    input: {
        fontSize: responsiveWidth(3.5),
        fontWeight: 'bold',
        flex: 1,
        color: colors.black,
        marginLeft: 10,
    },
    sortBtn: {
        marginHorizontal: 5,
        // height: 50,
        // width: 50,
        height: responsiveHeight(6),
        width: responsiveWidth(10),
        borderRadius: 5,
        backgroundColor: colors.violet,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 10,
        shadowColor: colors.black,
    },
    searchContainerItem: {
        // height: 60,
        backgroundColor: '#F0F0F0',
        borderRadius: 10,
        borderColor: colors.black,
        flexDirection: 'row',
        alignItems: 'center',
        height: heightHomeUpperContent,
        marginVertical: 10,
        elevation: 10,
    },
    inputItem: {
        fontSize: responsiveFontSize(1.5),
        fontWeight: '500',
        flex: 1,
        color: colors.black,
        // backgroundColor: colors.light,
        marginLeft: 10,
    },
    cartItem: {
        padding: 20,
        backgroundColor: colors.white,
        flexDirection: "row",
        justifyContent: "space-between",
        marginHorizontal: 20,
        marginVertical: 10,
        borderRadius: 10,
        shadowColor: colors.black,
        shadowOpacity: 0.26,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 10,
        elevation: 3,
    },
    cartItemImg: {
        //width: 80,
        width: responsiveWidth(25),
        //height: 80,
        height: responsiveHeight(15),
        resizeMode: "stretch",
        //backgroundColor: "white",
    },
    cartItemTitle: {
        fontSize: responsiveFontSize(1.5),
        marginVertical: 5,
        fontWeight: '800',
    },
    cartItemPrice: {
        fontSize: responsiveFontSize(1.2),
        // color: "coral",
        color: colors.violet,
        fontWeight: "bold",
    },
    cartItemAmount: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    cartItemAmountText: {
        fontSize: responsiveFontSize(1.5),
        fontWeight: "bold",
    },
    cartItemRemove: {
        alignItems: "center",
        justifyContent: "center",
    },
    cartItemRemoveButton: {
        marginHorizontal: 20,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    center: {
        flex: 1,
        // justifyContent: "center",
        // alignItems: "center",
        // textAlign: "center",
        backgroundColor: colors.lightGreyWhite,
        paddingHorizontal: 20,
        // marginHorizontal:20,
    },
    backBtn: {
        // backgroundColor: colors.smoke,
        padding: 5,
        // flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
    },
    iconBtn: {
        padding: 10,
        backgroundColor: colors.smoke,
        borderRadius: 10,
        shadowColor: colors.black,
        elevation: 10,
    },
    cardItemDetails: {
        flex: 1,
        backgroundColor: colors.white,
        // backgroundColor: '#EAF2F8',
        // backgroundColor: '#EAECEE',
        alignItems: 'center',
        width: widthCard,
        padding: 10,
        borderRadius: 40,
        elevation: 10,
    },
    imageIcon: {
        flex: 0.6,
        resizeMode: 'contain',
        // backgroundColor: '#EAF2F8',
        // height: 400,
        //width: widthImageIcon,
    },
    iconCart: {
        paddingVertical: 15,
        paddingHorizontal: 10,
        // backgroundColor: colors.smoke,
        borderRadius: 10,
        shadowColor: colors.black,
        elevation: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 20,
        backgroundColor: '#2B4C74',
        // elevation: 5,
        // shadowColor: colors.black,
        // color: colors.white,
    },
    sliderContainer: {
        width,
        height: '75%',
        // alignItems: 'center',
        backgroundColor: colors.shadow,
    },
    imageSlider: {
        // flex: 0.6,
        height: height / 4,
        width: '100%',
    },
    categoryContainer: {
        flexDirection: 'row',
        //marginTop: 20,
        // marginBottom: 0,
        justifyContent: 'space-between',
        // backgroundColor: 'red'
        // alignItems: 'baseline',
        //paddingHorizontal: 20,
        //marginLeft: 10,
        //flex: 1,
        alignSelf: 'flex-end'
    },
    categoryText: {
        fontSize: responsiveFontSize(1.5),
        color: 'grey',
        fontFamily: 'FredokaOne-Regular',
        // marginHorizontal: 20,
        // backgroundColor: 'yellow',
        //justifyContent: 'space-between',
    },
    categoryTextSelected: {
        color: colors.violet,
        paddingBottom: 5,
        // borderBottomWidth: 2,
        // borderColor: colors.violet,
        fontFamily: 'FredokaOne-Regular',
        fontSize: responsiveFontSize(1.8),
        // marginHorizontal: 20,
    },
});